### ISSUE TITLE
I think positive background-x is wrong

### ISSUE THREAD

**Issue by panlina** [tusharghate/angular-simple-sprite#4]
Say I have a sprite 400*100 containing 4 frames, `background-x` is 0 at the beginning, but the next time has `background-x: 100px`, which actually moves the range 300-400 in (because of the repeat)--notice that positive `background-x` moves the background away from the left, not towards it--thus it just jumps from the 1st frame to the last frame, then play backward. It should be negative.

**Comment by tusharghate** [comment]
Hi Panlina,

Sorry for the delay. I've pushed a fix and put up a new release (v1.1.0) that should resolve this problem.

Thanks,
Tushar
