### ISSUE TITLE
v0.0.6 not available anymore

### ISSUE THREAD

**Issue by ghost** [tusharghate/angular-simple-sprite#8]
One of our previous versions of our product uses v0.0.6 of angular-simple-sprite.
It seems like the releases and tags were deleted for this version and therefore we cannot build the previous version of our product.

Can you put those tags/releases back?

Thanks

**Comment by tusharghate** [comment]
Hi @JonasVDB-awingu,

Sorry for the late response!

All of the release versions and tags were re-organized and cleaned up. I *could* add v0.0.6 back, but is it possible for you to upgrade to the latest version (v1.1.2)? There should be no major differences between both versions besides some bug fixes. I assure you from here on out tags/releases will not be deleted without warning. Sorry again about the inconvenience.

**Comment by ghost** [comment]
hi @tusharghate,

We have updated to the latest version of angular-simple-sprite in the latest version of our product but older versions of our product reference the previous version of angular-simple-sprite. If we want to be able to build the exact same old version, we will need to be able to fetch version v0.0.6.

**Comment by tusharghate** [comment]
Ah, I see. No problem. I've re-created the v0.0.6 release for you, should be good to go now.

Thanks,
Tush

**Comment by ghost** [comment]
Awesome, thanks!
